# Generated by Django 5.2.4 on 2025-07-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='can_delete',
            field=models.BooleanField(default=False, help_text='Used in jupyter notebook'),
        ),
    ]
