# Generated by Django 5.2.4 on 2025-07-29 14:16

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_can_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768, null=True),
        ),
    ]
