# Generated by Django 5.2.4 on 2025-08-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost__content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
